# Common configuration
# Nacos Data ID: application-dev.yml
# Nacos Group: DEFAULT_GROUP

spring:
  main:
    allow-circular-references: true
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:localhost}:${NACOS_PORT:8848}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 200
        max-wait: -1ms
        max-idle: 10
        min-idle: 0

logging:
  level:
    com.value: debug
    org.springframework: warn

